repos:
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
        name: Format Nix files
        description: Format Nix code with nixpkgs-fmt
        entry: nixpkgs-fmt
        language: system
        files: \.nix$
        exclude: ^.*generated.*$