[devshell]
name = "Nix Home Manager"

packages = [
  "nano",
  "micro",
  "home-manager",
  "curl",
  "wget",
  "gnumake", "zlib.dev", "stdenv.cc", "openssl.dev", "libffi.dev", "pkg-config",
  "libffi", "libyaml"
]

packagesFrom = [
  "direnv"
]

[[commands]]
name = "switch"
category = "nixos-rebuild"
command = "sudo nixos-rebuild switch --flake ."
help = "If this machine is nixos, switch to the config"

[[commands]]
name = "apply"
category = "home-manager"
command = "home-manager switch --flake ."
help = "Apply home manager configuration"

[[commands]]
name = "check"
command = "nix flake check --all-systems"
help = "Check flake for errors"
