# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2284f472-82f2-42d7-8038-920cda0d7564";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8059-DDE9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  hardware.bluetooth.enable = true;                # Enables Bluetooth support
  hardware.bluetooth.powerOnBoot = true;           

  # NVIDIA driver configuration for Wayland
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   # Use the proprietary driver
  #   open = false; 
  #   # Install the stable NVIDIA driver package
  #   package = config.boot.kernelPackages.nvidiaPackages.stable;
  #   # Power management (helps with compatibility)
  #   powerManagement.enable = true;
  #   # Force composition pipeline to avoid issues
  #   forceFullCompositionPipeline = true;
  # };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp195s0f0u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp195s0f3u1u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
