#!/usr/bin/env bash
cursor_app="$(find $HOME/Applications -maxdepth 1 -name 'Cursor*.AppImage' | sort | head -n 1)"
if [[ -f "$cursor_app" ]]; then
    # If no arguments provided, just launch Cursor
    appimage-run "$cursor_app" "$*" > /dev/null &
    disown
    exit 0
fi

echo "Cursor AppImage not found."
exit 1
