#!/usr/bin/env bash
exec google-chrome-stable \
  --enable-features=UseOzonePlatform,WebAuthenticationRemoteDesktopSupport,WebAuthenticationCable \
  --disable-features=WebAuthenticationChromeOSAuthenticator \
  --ozone-platform=wayland \
  --enable-wayland-ime \
  --wayland-text-input-version=3 \
  --enable-logging=stderr \
  --enable-bluetooth-serial-communication \
  --enable-experimental-web-platform-features \
  --password-store=gnome-libsecret \
  "$@"
