{ modulesPath, pkgs, lib, ... }:

{
  imports =
    [
      # Include the default lxc/lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      #./lxd.nix - this has to be commented out from the system tarball
    ];
  boot.isContainer = true;

  # I had to suppress these units, since they do not work inside LXC
  systemd.suppressedSystemUnits = [
    "dev-mqueue.mount"
    "sys-kernel-debug.mount"
    "sys-fs-fuse-connections.mount"
  ];

  # A few packages I like to have around
  environment.systemPackages = with pkgs; [
    openssh
    vim
    tmux
    htop
    binutils
    man
  ];

  # Enable password-based SSH login for root
  services.openssh = {
    enable = true;
    settings = {
      AllowUsers = null; # everyone
      PasswordAuthentication = true; # this is just a sandbox
      PermitRootLogin = "yes";
    };
  };

  # from here on it's the same as the default tarball configuration

  networking = {
    # Proxmox/LXC: keep it simple and use dhcpcd (no systemd-networkd).
    # This avoids networkd/resolved interactions and matches the container defaults well.
    useNetworkd = lib.mkDefault false;
    dhcpcd.enable = lib.mkDefault true;
    useDHCP = lib.mkDefault true;
  };

  # Tailscale in LXC often lacks /dev/net/tun; use userspace networking by default.
  services.tailscale.interfaceName = lib.mkDefault "userspace-networking";

  systemd.services.console-getty = {
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStart = [
        ""
        "${pkgs.util-linux}/sbin/agetty --noclear console 115200,38400,9600 linux"
      ];
      Restart = "always";
      StandardInput = "tty";
      StandardOutput = "tty";
      TTYPath = "/dev/console";
    };
  };
}