[devshell]
name = "Nixos switch system"

packages = [
  "nano",
  "micro",
  "curl",
  "wget",
]

[[commands]]
name = "switch"
command = "sudo nixos-rebuild switch --flake ."
help = "If this machine is nixos, switch to the config"

[[commands]]
name = "check"
command = "nix flake check --all-systems"
help = "Check flake for errors"

[[commands]]
name = "iso"
help = "build iso for usb-stick"
command = "nix build .#nixosConfigurations.iso.config.system.build.isoImage"

[[env]]
name = "EDITOR"
value = "micro"
