{ modulesPath, config, pkgs, ... }:

{
  imports =
    [
      # Include the default lxc/lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      #./lxd.nix - this has to be commented out from the system tarball
    ];
  boot.isContainer = true;

  # I had to suppress these units, since they do not work inside LXC
  systemd.suppressedSystemUnits = [
    "dev-mqueue.mount"
    "sys-kernel-debug.mount"
    "sys-fs-fuse-connections.mount"
  ];

  # A few packages I like to have around
  environment.systemPackages = with pkgs; [
    openssh
    vim
    tmux
    htop
    binutils
    man
  ];

  # Enable password-based SSH login for root
  services.openssh = {
    enable = true;
    settings = {
      AllowUsers = null; # everyone
      PasswordAuthentication = true; # this is just a sandbox
      PermitRootLogin = "yes";
    };
  };

  # from here on it's the same as the default tarball configuration

  networking = {
    # Pick ONE networking stack to avoid dhcpcd and networkd fighting over interfaces.
    # This module configures `systemd.network` below, so we use networkd only.
    useNetworkd = true;
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.services.console-getty = {
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStart = [
        ""
        "${pkgs.util-linux}/sbin/agetty --noclear console 115200,38400,9600 linux"
      ];
      Restart = "always";
      StandardInput = "tty";
      StandardOutput = "tty";
      TTYPath = "/dev/console";
    };
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };
}